config/routes.rb
Rails.application.routes.draw do
  #root :to => 'home#index'


  root :to => 'home#index'
  
  get '/faq-articles', :to => 'faqcats#list'
  #get "/newposts" => 'faqposts#create', as: 'newposts'
 
  mount ShopifyApp::Engine, at: '/'
  resources :faqcats
  resources :faqposts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/faqcat.rb
class Faqcat < ApplicationRecord
	has_many :faqposts, dependent: :destroy
end

app/models/faqpost.rb
class Faqpost < ApplicationRecord
	belongs_to :faqcat
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include ShopifyApp::SessionStorage
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/faqcats_controller.rb
class FaqcatsController < ApplicationController
  before_action :set_faqcat, only: [:show, :edit, :update, :destroy]
  layout "list", only: [:list]


  # GET /faqcats
  # GET /faqcats.json
  def index
    @faqcats = Faqcat.all
  end

  # GET /faqcats/1
  # GET /faqcats/1.json
  def show
  end

  # GET /faqcats/new
  def new
    @faqcat = Faqcat.new
  end

  # GET /faqcats/1/edit
  def edit
  end

  def list
  #  @faqcats = Faqcat.all
  end

  # POST /faqcats
  # POST /faqcats.json
  def create
    @faqcat = Faqcat.new(faqcat_params)
    #binding.pry          # Execution will stop here.

    respond_to do |format|
      if @faqcat.save
        #format.html { redirect_to @faqcat, notice: 'Faqcat was successfully created.' }
        #format.json { render :show, status: :created, location: @faqcat }
        format.html { redirect_to root_url, notice: 'Category added successfully.' }
      else
        #format.html { render :new }
        #format.json { render json: @faqcat.errors, status: :unprocessable_entity }
        format.html { redirect_to root_url, notice: 'Something went wrong.' }
        
      end
    end
  end

  # PATCH/PUT /faqcats/1
  # PATCH/PUT /faqcats/1.json
  def update
    respond_to do |format|
      if @faqcat.update(faqcat_params)
        format.html { redirect_to root_url, notice: 'Category updated successfully.' }
        #format.html { redirect_to @faqcat, notice: 'Category was successfully updated.' }
        #format.json { render :show, status: :ok, location: @faqcat }
      else
        format.html { redirect_to root_url, notice: 'Something went wrong.' }
        #format.html { render :edit }
        #format.json { render json: @faqcat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faqcats/1
  # DELETE /faqcats/1.json
  def destroy
    @faqcat.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Faqcat was successfully destroyed.' }
      #format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faqcat
      @faqcat = Faqcat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faqcat_params
      params.require(:faqcat).permit(:title)
    end
end

app/controllers/faqposts_controller.rb
class FaqpostsController < ApplicationController
  before_action :set_faqpost, only: [:show, :edit, :update, :destroy]

  # GET /faqposts
  # GET /faqposts.json
  def index
    @faqposts = Faqpost.all
  end

  # GET /faqposts/1
  # GET /faqposts/1.json
  def show
  end

  # GET /faqposts/new
  def new
    @faqpost = Faqpost.new
  end

  # GET /faqposts/1/edit
  def edit
  end

  # POST /faqposts
  # POST /faqposts.json
  def create
    @faqpost = Faqpost.new(faqpost_params)
    #binding.pry 
    respond_to do |format|
      if @faqpost.save
        format.html { redirect_to root_url, notice: 'Article added successfully.' }
        #format.html { redirect_to @faqpost, notice: 'Faqpost was successfully created.' }
        #format.json { render :show, status: :created, location: @faqpost }
      else
        format.html { redirect_to root_url, notice: 'Something went wrong.' }
        #format.html { render :new }
        #format.json { render json: @faqpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faqposts/1
  # PATCH/PUT /faqposts/1.json
  def update
    respond_to do |format|
      if @faqpost.update(faqpost_params)
        #format.html { redirect_to root_url, notice: 'Faqpost was successfully updated.' }
        #format.json { render :show, status: :ok, location: @faqpost }
        format.html { redirect_to root_url, notice: 'Article updated successfully.' }
      else
        format.html { redirect_to root_url, notice: 'Something went wrong.' }
        #format.html { render :edit }
        #format.json { render json: @faqpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faqposts/1
  # DELETE /faqposts/1.json
  def destroy
    @faqpost.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Faqpost was successfully destroyed.' }
      #format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faqpost
      @faqpost = Faqpost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faqpost_params
      params.require(:faqpost).permit(:title, :content, :faqcat_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ShopifyApp::AuthenticatedController
  def index
    @products = ShopifyAPI::Product.find(:all, params: { limit: 10 })
    @webhooks = ShopifyAPI::Webhook.find(:all)


     @faqposts = Faqpost.all
     @faqcats = Faqcat.all

    #redirect_to :controller => 'faqposts', :action => 'new'
    #@faqpost = Faqpost.new
    #render :controller => 'faqposts', :action => 'new'
   # @faqpost = Faqpost.new
    #render 'faqposts/new'
   # render :partial => 'faqposts/new'

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/faqcats_helper.rb
module FaqcatsHelper
end

app/helpers/faqposts_helper.rb
module FaqpostsHelper
end

app/views/faqcats/_new_form.html.erb
<%= form_with(model: faqcat, local: true) do |form| %>
  <% if faqcat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(faqcat.errors.count, "error") %> prohibited this faqcat from being saved:</h2>

      <ul>
      <% faqcat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :faqcat_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/faqcats/edit.html.erb
<h1>Editing Faqcat</h1>

<%= render 'form', faqcat: @faqcat %>

<%= link_to 'Show', @faqcat %> |
<%= link_to 'Back', faqcats_path %>

app/views/faqcats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Faqcats</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @faqcats.each do |faqcat| %>
      <tr>
        <td><span><%= faqcat.id %> </span><%= faqcat.title %></td>
        <%  %>
        <table>
          <tr>
            <% Faqpost.where(faqcat_id: faqcat.id).each do |catfaq| %>
                <td><span><%= catfaq.id %> </span><%= catfaq.title %></td>
            <% end %>    
          </tr>
        </table>
        

        <td></td>
        <td><%= link_to 'Show', faqcat %></td>
        <td><%= link_to 'Edit', edit_faqcat_path(faqcat) %></td>
        <td><%= link_to 'Destroy', faqcat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Faqcat', new_faqcat_path %>

app/views/faqcats/new.html.erb
<h1>New Faqcat</h1>

<%= render 'new_form', faqcat: @faqcat %>

<%= link_to 'Back', faqcats_path %>

app/views/faqcats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @faqcat.title %>
</p>

<%= link_to 'Edit', edit_faqcat_path(@faqcat) %> |
<%= link_to 'Back', faqcats_path %>

app/views/faqposts/_form.html.erb
<%= form_with(model: faqpost, local: true) do |form| %>
  <% if faqpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(faqpost.errors.count, "error") %> prohibited this faqpost from being saved:</h2>

      <ul>
      <% faqpost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.collection_select(:faqcat_id, Faqcat.all, :id, :title, {prompt: "Choose a category" }) %><br>
  </div> 

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :faqpost_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :faqpost_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/faqposts/edit.html.erb
<h1>Editing Faqpost</h1>

<%= render 'form', faqpost: @faqpost %>

<%= link_to 'Show', @faqpost %> |
<%= link_to 'Back', root_path %>

app/views/faqposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Faqposts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<pre>
  <tbody>
    <% @faqposts.each do |faqpost| %>
      <tr>
        <td><%= faqpost.title %></td>
        <td><%= faqpost.content %></td>
        <td><%= link_to 'Show', faqpost %></td>
        <td><%= link_to 'Edit', edit_faqpost_path(faqpost) %></td>
        <td><%= link_to 'Destroy', faqpost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Article', new_faqpost_path %>

app/views/faqposts/new.html.erb
<h1>New Faqpost</h1>

<%= render 'form', faqpost: @faqpost %>

<%= link_to 'Back', root_path %>

app/views/faqposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cat:</strong>
  <% @faqcat = Faqcat.find(@faqpost.faqcat_id)  %>
  <span id="<%= @faqpost.faqcat_id %>"><%= @faqcat.title %></span>
</p>

<p>
  <strong>Title:</strong>
  <%= @faqpost.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @faqpost.content %>
</p>

<%= link_to 'Edit', edit_faqpost_path(@faqpost) %> |
<%= link_to 'Back', faqposts_path %>

app/views/home/_cat_form.html.erb
<%= form_with(model: faqcat, local: true) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :faqcat_title %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Category', class: 'Polaris-Button' %>
  </div>
<% end %>

app/views/home/_catedit_form.html.erb
<%= form_for(faqcat, :url => {:controller => 'faqcats',:action => 'update', :id => fcat_id}) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :faqcat_title %>
  </div>

  <div class="actions">
    <%= form.submit 'Update Category', class: 'Polaris-Button' %>
  </div>
<% end %>

app/views/home/_faq_form.html.erb
<%= form_with(model: faqpost, local: true) do |form| %>
  <div class="field">
    <%= label_tag(:faqcat_id, "Select Category:") %>
    <%= form.collection_select :faqcat_id, Faqcat.all, :id, :title, {:selected => fcat_id}, {class: 'form-control  m-b' } %>
  </div> 

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :faqpost_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, :class => "tinymce", :rows => 40, :cols => 120 %>
      </div>
  
  <div class="actions">
    <%= form.submit 'Create FAQ', class: 'Polaris-Button' %>
  </div>
<% end %>

app/views/home/_faqedit_form.html.erb
<%= form_for(faqpost, :url => {:controller => 'faqposts',:action => 'update', :id => fpost_id}) do |form| %>
  <div class="field">
    <%= label_tag(:faqcat_id, "Select Category:") %>
    <%= form.collection_select :faqcat_id, Faqcat.all, :id, :title, {:selected => fcat_id}, {class: 'form-control  m-b' } %>
  </div> 

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :faqpost_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, :class => "tinymce", :rows => 40, :cols => 120 %>
  </div>
  
  <div class="actions">
      <%= form.submit 'Update FAQ', class: 'Polaris-Button' %>
  </div>
<% end %>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Faqapp</title>
        
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link rel="stylesheet" href="https://sdks.shopifycdn.com/polaris/1.9.1/polaris.min.css" />
        <%= stylesheet_link_tag "custom-style" %>
        <%= javascript_include_tag "customtag" %>

        <% content_for :javascript do %>
          <script type="text/javascript">
            ShopifyApp.ready(function(){
                ShopifyApp.Bar.initialize({ title: "Home" });
            });

            tinyMCE.init({
                selector: 'textarea.editor'
              });

          </script>
        <% end %>
    </head>
    <body>

        <div class="app-bar-content">
            <% Faqcat.all.each do |faqcat| %>
                <ul>
                    <li>
                        <div class="category-sect clearfix">
                            <div class="left-cont-list">
                                <span><%= faqcat.title %></span>
                                <% ceditlink = edit_faqcat_path(faqcat).gsub("/","-") %>
                                <div id="<%= ceditlink %>" class="form-edit-sect faq-form" style="display:none;">
                                    <%= render partial: 'catedit_form', locals: {:faqcat => faqcat, :fcat_id => faqcat.id} %>
                                </div>
                            </div>

                            <div class="right-cont-list">
                                <!-- Category Edit Form -->
                                <%= link_to 'Edit', edit_faqcat_path(faqcat), :remote => true, rel: edit_faqcat_path(faqcat), class: 'Polaris-Button tap-edit_sect' %>

                                <!-- Category Destroy Form -->
                                <span><%= link_to 'Destroy', faqcat, method: :delete, data: { confirm: 'Are you sure?' }, class: 'Polaris-Button', :remote => true %></span>

                            </div>
                        </div>
                        
                        <div class="faq-article-sect clearfix">
                            <!-- Category's FAQ Listing -->    
                            <ul style="padding-left:30px;">
                                <% Faqpost.where(faqcat_id: faqcat.id).each do |catfaq| %>
                                    <li>
                                        <div class="faq-sect clearfix">
                                            <div class="left-cont-list">
                                                <span><%= catfaq.title %></span>
                                                <% editlink = edit_faqpost_path(catfaq).gsub("/","-") %>
                                                <div id="<%= editlink %>" class="form-edit-sect faq-form" style="display:none;">
                                                    <%= render partial: 'faqedit_form', locals: {:faqpost => catfaq, :fpost_id => catfaq.id, :fcat_id => faqcat.id} %>
                                                </div>
                                            </div>
                                            <div class="right-cont-list">
                                                <!-- FAQ Edit Form -->
                                                <%= link_to 'Edit', edit_faqpost_path(catfaq), :remote => true, rel: edit_faqpost_path(catfaq), class: 'Polaris-Button tap-edit_sect' %>
                                                <%= link_to 'Destroy', catfaq, method: :delete, data: { confirm: 'Are you sure?' }, class: 'Polaris-Button', :remote => true %>
                                                <!-- FAQ Destroy Form -->
                                                <span></span>
                                            </div>
                                        </div>
                                    </li> 
                                <% end %>
                                <!-- FAQ ADD Form -->
                                <div class="new-article-sect clearfix">
                                    <li>
                                        <%= link_to 'Add New Article', new_faqpost_path, :remote => true, rel: 'tap-new_faq', class: 'tap-new_sect' %>
                                        <% @faqpost = Faqpost.new %>
                                        <div id="tap-new_faq" class="form-new-sect faq-form" style="display:none;">
                                            <div id="wysihtml5-toolbar">
                                                <%= render partial: 'faq_form', locals: {:faqpost => @faqpost, :fcat_id => faqcat.id} %>
                                            </div>
                                        </div>
                                    </li>    
                                </div>                                
                            </ul>
                        </div>
                    </li>

                </ul>

            <% end %>

            <!-- Category Add Form -->
            <div class="catnew-sect clearfix">
                <ul class="cat-new">
                    <li>
                        <%= link_to 'Add New Category', new_faqcat_path, :remote => true, rel: 'tap-new_cat', class: 'tap-new_sect' %>
                        <div id="tap-new_cat" class="form-new-sect" style="display:none;">
                            <% @faqcat = Faqcat.new %>
                            <%= render 'cat_form', faqcat: @faqcat %>
                        </div>
                    </li>
                </ul>
            </div>
        </div>

        <%= tinymce %>

    </body>
</html>

app/views/home/show.html.erb
<div class="faq-list-sect">
	<% @faqcats.each do |faqcat| %>
	    <div class="faqart-listing">
	        <h2><%= faqcat.title %></h2>
	        <div class="clearfix faqpost-content">   
	            <ul>
	                <% Faqpost.where(faqcat_id: faqcat.id).each do |catfaq| %>
	                    <li class="faq-listing">
	                        <div class="faq-question"><%= catfaq.title %></div>
	                        <div class="faq-answer" style="display:none;"><%= raw catfaq.content %></div>
	                    </li> 
	                <% end %>              
	            </ul>
	        </div>
	    </div>
	<% end %>
</div>

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
<script type="text/javascript">
  var eventName = typeof(Turbolinks) !== 'undefined' ? 'page:change' : 'DOMContentLoaded';

  document.addEventListener(eventName, function() {
    <% if flash[:notice] %>
      ShopifyApp.flashNotice("<%= j flash[:notice].html_safe %>");
    <% end %>

    <% if flash[:error] %>
      ShopifyApp.flashError("<%= j flash[:error].html_safe %>");
    <% end %>
  });
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Faqapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "custom-style" %>
    <%= javascript_include_tag "customtag" %>

    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <% application_name = ShopifyApp.configuration.application_name %>
    <title><%= application_name %></title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>

    <script type="text/javascript">
      ShopifyApp.init({
        apiKey: "<%= ShopifyApp.configuration.api_key %>",
        shopOrigin: "<%= "https://#{ @shop_session.url }" if @shop_session %>",
        debug: <%= Rails.env.development? ? 'true' : 'false' %>,
        forceRedirect: true
      });
    </script>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>

app/views/layouts/list.html.erb
<link rel="stylesheet" media="screen" href="https://71d7274c.ngrok.io/assets/custom-style.css">
<script src="https://71d7274c.ngrok.io/assets/customtag.js"></script>
<div class="faq-list-sect">
	<% Faqcat.all.each do |faqcat| %>
	    <div class="faqart-listing">
	        <h2><%= faqcat.title %></h2>
	        <div class="clearfix faqpost-content">   
	            <ul>
	                <% Faqpost.where(faqcat_id: faqcat.id).each do |catfaq| %>
	                    <li class="faq-listing">
	                        <div class="faq-question"><%= catfaq.title %></div>
	                        <div class="faq-answer" style="display:none;"><%= raw catfaq.content %></div>
	                    </li> 
	                <% end %>              
	            </ul>
	        </div>
	    </div>
	<% end %>
</div>